[package]
name = "modern-ecnu-thesis"
version = "0.3.4"
entrypoint = "lib.typ"
authors = ["Juntong Chen <@jtchen2k>"]
license = "MIT"
description = "华东师范大学学位论文模板。Modern East China Normal University Thesis Template."
repository = "https://github.com/jtchen2k/modern-ecnu-thesis"
keywords = ["East China Normal University", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"